### ISSUE TITLE
Error after upgrading to 3.2.0

### ISSUE THREAD

**Issue by dougg0k** [typescript-language-server/typescript-language-server#689]
Hi, 

In v3.1.0, the error are not there.

`typescript-language-server --stdio`

```
> node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module '/home/user/.local/share/pnpm/global/5/node_modules/typescript-language-server/lib/cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by rchl** [comment]
The library path is `../lib/cli.mjs`, not `../lib/cli.js` and it has been like that for many versions now. Certainly not new to 3.2.0.

**Comment by dougg0k** [comment]
I updated to 3.2.0 and the problem started, after, I downgraded to 3.1.0, problem was gone.

**Comment by rchl** [comment]
Think there is something wrong with your setup then. Try re-installing or something.

The `typescript-language-server` is a symlink in your system and it should point to */lib/cli.mjs` and it does here:

```
lrwxr-xr-x   1 xxx  xxx        58 Feb 16 17:12 typescript-language-server@ -> ../lib/node_modules/typescript-language-server/lib/cli.mjs
```

**Comment by dougg0k** [comment]
Not really, this was just a global install and executed with `--stdio`. Never had any issues before, same setup, and it's not the first update. But it's fine, I can still use 3.1.0.

**Comment by predragnikolic** [comment]
I tried installing this package globally,
```
$ typescript-language-server --version
3.2.0
```

I run:
```
typescript-language-server --stdio
```
and it works without any issues.

Here is my node version:
```
node -v 
v16.16.0
```

**Comment by rchl** [comment]
You are using pnpm. Maybe some bug there. Just check where `typescript-language-server` is with `which typescript-language-server` and then open that file in the editor and edit it to change `.js` to `.mjs`.

Or delete the file manually and re-install the server.

Nothing related has changed in the new version.

**Comment by dougg0k** [comment]
I removed and installed again instead of doing an update, it worked. Seems like the pnpm update caused the problem.
